name: Deploy on aws EC2

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: aws
    defaults:
      run:
        working-directory: app/api
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install client dependencies
        working-directory: app/client
        run: npm install
      - name: SSH Setup
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          private-key: ${{ secrets.AWS_KEY }}
          private-key-name: aws.pem
      - name: Deploy
        env:
          aws_host: ${{ secrets.EC2_HOST }}
          rds_host: ${{ secrets.RDS_HOST }}
          rds_user: ${{ secrets.RDS_USER }}
          rds_pass: ${{ secrets.RDS_PASS }}
        run: ./gradlew awsDeploy
