name: Deploy on aws EC2

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: aws
    defaults:
      run:
        working-directory: app/api
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install client dependencies
        working-directory: app/client
        run: npm install
      - name: Copy ssh key
        env:
          aws.key: ${{ secrets.AWS_KEY }}
        run: echo $aws.key > aws.pem
      - name: Deploy
        env:
          aws.host: ${{ secrets.EC2_HOST }}
          rds.host: ${{ secrets.RDS_HOST }}
          rds.user: ${{ secrets.RDS_USER }}
          rds.pass: ${{ secrets.RDS_PASS }}
        run: ./gradlew awsDeploy
