name: E2E tests

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: e2e-test-db
          postgresql user: e2e-user
          postgresql password: e2e-pass
      - name: Install client dependencies
        working-directory: app/client
        run: npm install
      - name: Build client
        working-directory: app/api
        run: ./gradlew buildClient
      - name: Build Server
        working-directory: app/api
        run: ./gradlew build -x test
      - name: Apply db patch
        working-directory: app/api
        run: git apply src/test/resources/E2E_tests_db.patch
      - name: Init db data
        working-directory: app/api
        run: |
          ./gradlew bootRun & sleep 10 && ./gradlew --stop
          PGPASSWORD=e2e-pass psql -h localhost -p 5432 -U e2e-user -d e2e-test-db -f src/test/resources/init_test_data.sql
      - name: Cypress tests
        working-directory: app
        run: |
          cd api && ./gradlew bootRun & sleep 10 && cd client && npm run test:cypress_e2e
          cd ../api && ./gradlew --stop
      - name: Cypress artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress_artifacts
          path: app/client/cypress/**
      - name: Playwright tests
        working-directory: app/client
        run: npm run test:playwright_e2e
