name: Frontend react tests

on:
  push:
    branches: [ master ]
    paths:
      - 'app/client/**'
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Test
        run: npm run test:react
