name: Tinkoff perftest. Part 2

on:
  push:
    branches: [ master ]
    paths:
      - 'TinkoffPerfWorkshop/Part2/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  perf_job:
    runs-on: ubuntu-latest
    env:
      # simulation config
      ORGANISATION: "ru.tinkoff.load"
      SERVICE_NAME: "myservice"
      SIMULATION: "MaxPerformance"
      baseUrl: "http://localhost:7000"

      # logs & metrics config
      CONSOLE_LOGGING: "ON"
      GRAPHITE_HOST: "influxdb"
      GRAPHITE_PORT: "2003"
      INFLUX_PREFIX: "experiment"

      # cache config
      SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy -Dconfig.override_with_env_vars=true"
      COURSIER_CACHE: sbt-cache/coursier
    defaults:
      run:
        working-directory: TinkoffPerfWorkshop/Part2
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
    - name: Cache sbt files
      uses: actions/cache@v2
      with:
        path: |
          sbt-cache/.ivy/cache
          sbt-cache/.boot
          sbt-cache/.sbtboot
          sbt-cache/coursier
        key: ${{ github.ref }}
    - name: Up mock server
      run: |
        cd docker
        docker-compose up -d
        docker-compose ps
    - name: Test
      if: env.ORGANISATION != '' && env.SERVICE_NAME != '' && env.SIMULATION != ''
      run: |
        rm -rf target/gatling/*
        echo "Runing simulation $ORGANISATION.$SERVICE_NAME.$SIMULATION"
        sbt "gatling:testOnly $ORGANISATION.$SERVICE_NAME.$SIMULATION"
      env:
        JAVA_OPTS: "-Dgatling.charting.noReports=true"
    - name: Test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test_artifacts
        path: TinkoffPerfWorkshop/Part2/target/gatling/**/simulation.log
    - name: Collect pages
      run: |
        sbt "gatling:generateReport"
        mkdir -p public/
        cp -r target/gatling/**/index.html public/
        cp -r target/gatling/**/req_* public/
        cp -r target/gatling/**/js/ public/
        cp -r target/gatling/**/style/ public/
        rm -rf target/gatling/*
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: tinkoff-pages
        FOLDER: TinkoffPerfWorkshop/Part2/public
        TARGET_FOLDER: part2
        CLEAN: true
